### ISSUE TITLE
Make it work with Nodejs 4.0

### ISSUE THREAD

**Issue by etopian** [aacerox/node-rest-client#100]
This returns a buffer object as data instead of parsing the JSON output.

```
client.get("https://voip.ms/api/v1/rest.php", args,
            function(data, response){
            // parsed response body as js object
            console.log(JSON.parse(data.toString()));
            // raw response
            //console.log(response);
});
```

Running JSON.parse on the data.toString() works but the returned object as data is a Buffer.

https://nodejs.org/api/buffer.html

**Comment by quocvu** [comment]
I noticed the same problem.  `data` is a `Buffer` not a JSON object.  It is also happening under Node 0.10

**Comment by kim3er** [comment]
Until this fixed, my work around is (placed at the top of the callback):

```
data = JSON.parse(data.toString());
```

**Comment by aacerox** [comment]
fixed with pull request

**Comment by nickmarx12345678** [comment]
believe I'm still seeing this in node 0.10
