### ISSUE TITLE
Support for HEAD & OPTIONS HTTP method

### ISSUE THREAD

**Issue by sirhanshafahath** [aacerox/node-rest-client#102]
Hello,

  It would be nice to see this module support the HEAD & OPTIONS HTTP methods as well as it would be an added bonus to support custom HTTP methods like PURGE or any custom HTTP methods.

PS: HEAD is useful when the underlying api supports both GET & HEAD methods on the same endpoint. A HEAD will return information about the object as Response Headers, where as GET will return the actual object, which might by of several MB of data.

Thanks

**Comment by aacerox** [comment]
Hi
in next version there will be support for custom HTTP Methods.
thnx.
