### ISSUE TITLE
For POST requests "data" attribute does not show up on the server request object

### ISSUE THREAD

**Issue by cold-gin** [aacerox/node-rest-client#104]
I am setting the "data" attribute on the args json when making a post request, but this attribute is not set as the body of the server request, or any other attribute of the server that I can see. 

In tracking the code, it looks like it does:

if(options.data) request.write(this.prepareData(options.data)); 

but I do not see options.data show up on my server request object anywhere. Can you please advise as to where the "data" attribute gets mapped to on the server request?

Thank you

**Comment by NNM11** [comment]
+1.  - I got an error in ;

       if(options.data) request.write(this.prepareData(options.data));
                                                                    ^
TypeError: Object #<ClientRequest> has no method 'prepareData'

**Comment by xfg** [comment]
+1

**Comment by aacerox** [comment]
solved with pull request.
