### ISSUE TITLE
When XML is sent without root, how can I get both nodes?

### ISSUE THREAD

**Issue by wyattbiker** [aacerox/node-rest-client#106]
So if I have the following XML string as the data response (without a root or think of it as 3 different roots) coming back from an events queue.
```
<root>data1</root><root>data2</root><root>data3</root>
```
I will only get {"root":"data1"} with the Client.get().  Any ideas how to get all three of them?

E.g.
```
Client.get(MY_URL, args, function (data, response){
... only  {"root":"data1"}  shows up in the data object
}
```

**Comment by aacerox** [comment]
that's because your response is malformed, it should contain a main root element that contains all three elements. With your response the XML parser treat first root as the whole document
```xml
<mainroot>
<root>data1</root>
<root>data2</root>
<root>data3</root>
</mainroot>
