### ISSUE TITLE
<Buffer > in data output

### ISSUE THREAD

**Issue by eddyLazar** [aacerox/node-rest-client#107]
<Buffer > - console.log output on `data` attribute

**Comment by theGrue** [comment]
This issue appears whenever a server returns a Content-Type of "application/json; charset=utf-8", as Express >= 4.3.0 and many others do. The author stubbornly refuses all pull requests to change this, making this library broken "out of the box" for many users.

See #9, #12, #17, #34, #39, #42, #53, #74, #75, #81, #82, #83, #84, #89, #90, #92, #94, #98, and #100 for more details.

**Comment by aacerox** [comment]
fixed with pull requests

**Comment by Kaushalop** [comment]
Which pull requests are you referring to @aacerox . I got the same error while working on it today !
