### ISSUE TITLE
Allow for options to pass through to XML parseString function for tailoring XML parsing

### ISSUE THREAD

**Issue by shusak** [aacerox/node-rest-client#110]
I would like the capability to pass through options to the xml2js parseString to tailor the XML parsing that is happening there. 

I will try and submit a pull request with this shortly.

**Comment by shusak** [comment]
@aacerox Any thoughts on this yet? Was hoping to get it pulled in so I can move from my fork into your project

**Comment by nyanpasu** [comment]
would be very nice to have this feature in. though @shusak you have whitespace issues in your commit.

**Comment by shusak** [comment]
@nyanpasu fixed up the spacing issues after merging into my fork

**Comment by aacerox** [comment]
Hi

this will be available in version 3.0.1 that will be released tonight (GMT+1).

Thanks.
