### ISSUE TITLE
reusable sessions

### ISSUE THREAD

**Issue by bchr02** [aacerox/node-rest-client#113]
I am trying to use cookies that have been received back after one request in subsequent requests, just like a browser would. Is this possible with the current api? Thanks.

**Comment by bchr02** [comment]
Never mind. Using https://github.com/request/request instead.

**Comment by Kostanos** [comment]
You can just send cookie inside header:
```
client.get(url, {
  headers: {
    Cookie: aaa=bbb; ccc=ddd
  }
}
```

According to HTTP headers specification: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cookie
