### ISSUE TITLE
<Buffer > in data output

### ISSUE THREAD

**Issue by webfxmasta** [aacerox/node-rest-client#115]
This was claimed to be fixed by a pull-request last year, but it is still occurring, especially in the special case where a custom mimetype is defined.  I am using the latest revision (1.8.0) of the package running on Node 5.4.1.  
Ex.

```
'use strict';
var client = require('node-rest-client').Client;
var options = {
        user:           'user',
        password:       'pass',
        mimetypes:      {json: ['application/json', 'application/vnd.localytics.v1+hal+json;type=ResultSet; charset=utf-8']},
        requestConfig:  {timeout: 2000},
        responseConfig: {timeout: 2000}
    };
var requestArgs = {headers: {'Accept': 'application/json'}};
new client(options).get('https://api.localytics.com/v1/query?app_id=1&metrics=users', requestArgs, function(data, response) {
   if(!response.statusCode >= 400) {
    console.log(data);
   }
}
```

This results in a <Buffer ...> output to the console.

**Comment by alrek-consulting** [comment]
I can confirm this too.
I have written a small REST client app, using node-rest-client. 

The API I am consuming is responding with mime-type: "**application/vnd.vegvesen.nvdb-v1+json**".

I have to manually cast the data to an Object, by doing:
`JSON.parse(data.toString());`

https://github.com/alrek-consulting/node-vegvesen/blob/master/vegvesen.js#L90

**Comment by alrek-consulting** [comment]
There doesn't seem to be much activity from the maintainers here. But I will look at the issue later, and add a pull request

**Comment by alrek-consulting** [comment]
As it appears right now, it seems that in src/node-rest-client.js on [line 348](https://github.com/aacerox/node-rest-client/blob/master/lib/node-rest-client.js#L348), it tests the mimetype agains a pre-defined array. It would probably be better to test it against a pattern.

Like:
`(?:(?:application|text)\/)(?:.+\+)?(?:jsonp?|plain|xml|javascript)(?:.+)?`

**Comment by dreamersp** [comment]
Any intention to fix this?
It's still happening with version 2.0.1 when contacting with a .NET MVC API.

**Comment by fpereira1** [comment]
This may be a solution to some, you can use your own mimetypes:

```
var client = new Client({
      mimetypes: {
       json: ['application/json', 'application/json; charset=utf-8'],
       xml: ['application/xml', 'application/xml; charset=utf-8']
     }
});
```

**Comment by dreamersp** [comment]
@fpereira1 I managed to overcome it using "application/json;charset=UTF-8" for the mimetype, as well as 'application/json; charset=utf-8'.

It seems that .NET MVC WebAPI sometimes returns 'application/json; charset=utf-8' but on last update most times "application/json;charset=UTF-8" as I saw in the inspection of the headers returned.

Thanks for your comment that pointed me toward this.

**Comment by sapyx** [comment]
any news?

**Comment by sandorfr** [comment]
yes I wouldn't have suspected the need to use custom mimetypes to support charset or vnd mime types.

**Comment by sandorfr** [comment]
Has it been addressed @aacerox?

**Comment by aacerox** [comment]
well, I think previous comments gives differents workarounds to overcome this issue and also in new version planned to be release before christmas there's a minor fix in content-type parsing.
