### ISSUE TITLE
HTTPS REQUEST- UNABLE TO VERIFY CERTIFICATE

### ISSUE THREAD

**Issue by 2Marks** [aacerox/node-rest-client#126]
When doing POST request via https -- it throws out error -- unable to verify certificate.
![git-https](https://cloud.githubusercontent.com/assets/12138334/16977331/4a075a94-4e4d-11e6-80d4-b0e79dc59de4.PNG).

Any help appreciated.

**Comment by xfrustix** [comment]
Is there news about this problem? 
I have also the problem - have a URL with https and the output gives an "authorizationError: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'.

I have search in google - but nothing is working correctly - always same message.
I also have put this before set Client:
- process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";

but also the same problem.

With the Insomnia-REST-Client I become without any problems all the data.

Just another info - in vbscript it gives the folloing statement to suppress the cert warning
- httpObj.setOption 2, 13056 'suppress cert warning

I don't want make it with vb or c# or other - I like node. ;-)

Any idea?

Thanks and best regards
frusti

**Comment by 2Marks** [comment]
I fixed it by setting "rejectUnauthorized=false" in the apioptions circled below. its stated in the node js documentation as node tends to verify the server certificate.

![rejectunauthorized](https://cloud.githubusercontent.com/assets/12138334/19549569/f95c1ef2-969c-11e6-89b6-8b12a4657874.PNG)

`<a href="https://nodejs.org/api/https.html#https_https_request_options_callback">node docs</a>`

**Comment by 2Marks** [comment]
Kindly checkout the github issue i have updated it with the solution.

https://github.com/coolaj86/node-ssl-root-cas/issues/26#issuecomment-239136653
