### ISSUE TITLE
Support for URL encoded POST data

### ISSUE THREAD

**Issue by gabeosx** [aacerox/node-rest-client#128]
It would be useful to have functionality to be able to optionally encode POST data as application/x-www-form-urlencoded, for services that expect form data, rather than JSON. 

For example

```
data {
arg1: 'value',
arg2: 'value'
}
```

becomes
`arg1=value&arg2=value`

**Comment by aacerox** [comment]
this is available since version 3.0 through URL-ENCODED serializer.

Please give it a try and let me know if it works.

thnx
