### ISSUE TITLE
Issue with defined methods

### ISSUE THREAD

**Issue by micsen** [aacerox/node-rest-client#135]
`var url="http://www.w3schools.com/html/action_page.php";
var args={'lastname': 'mouse'}
client.registerMethod("api", url ,"GET");

client.methods.api(args, function (data, response) {
    console.log(response);
    if(Buffer.isBuffer(data)){
      data = data.toString('utf8');
    }
    console.log(data);
  });
`
Tells me there was no get data sent with the request

**Comment by micsen** [comment]
Actually after attempting a simple get i also end up with the same result.

**Comment by 3rand** [comment]
I also confirm the same behavior.
I also tried several definitions of:
mimetypes: {
        json: ['application/json', 'application/json;charset=utf-8', 'application/json; charset=utf-8', 'application/json;charset=UTF-8', 'application/json; charset=UTF-8'],
    }

**Comment by aacerox** [comment]
Hi
you're creating the wrong args object. correct way is (as you can see in docs):
```javascript
var args={
	parameters:{'lastname': 'mouse'}
};
```
Please read the documentation carefully before posting an issue.

Thanks.
