### ISSUE TITLE
Not getting status code of api

### ISSUE THREAD

**Issue by tshah09** [aacerox/node-rest-client#137]
Hi,

`var req1 = client.get("http://remote.site/rest/xml/method", {}, function (data, response) {
    // parsed response body as js object 
    console.log(data);
    // raw response 
    console.log(response);
});
`
My return response is `{message: 'something went wrong'}`.

But i want to check it with status code and not message. I tried "data.httpStatus" or "data.statusCode".
But none is working.
Any way to get status code ?

**Comment by antoine-pous** [comment]
Hi,

`statusCode` is available in response object ;)
```javascript
client.get("http://remote.site/rest/xml/method", {}, function (data, response) { 
  console.log(response.statusCode); // 200
});
```

**Comment by tshah09** [comment]
@antoine-pous Thank you
