### ISSUE TITLE
Don't pass Content-Length: 0 when using GET

### ISSUE THREAD

**Issue by rofr** [aacerox/node-rest-client#140]
From the http 1.1 standard at https://tools.ietf.org/html/rfc7230#section-3.3.2

>A user agent SHOULD NOT send a Content-Length header field when the request message does not contain a payload body and the method semantics do not anticipate such a body.

**Comment by rofr** [comment]
PR #141 resolves this issue

**Comment by aacerox** [comment]
This was set because some servers (Apache , Nginx) don't process request properly if no Content-Length header is set.
