### ISSUE TITLE
Support custom response formats additionally to XML and JSON

### ISSUE THREAD

**Issue by Apollon77** [aacerox/node-rest-client#142]
When communicating with a server with a custom response format currently it is needed to convert that on each response.

It would be a great feature to allow the registration of "custom response format handlers" where e.g. a "isFormat" and "convertToJSon" callbacks can be configured directly on the client level (so only once). This is then automatically used before returning the response object ...

**Comment by aacerox** [comment]
With new parser feature released on 3.0 versión  you can create your own custom response parsers.

thnx.
