### ISSUE TITLE
Handle Big Number in Json Response for Get Request

### ISSUE THREAD

**Issue by ajinkyadesai** [aacerox/node-rest-client#149]
Currently Json.parse used for sending Json response of Get request , could not handle Big numbers 

e.g. for field value  12345678876543218888 , we get response as 1234567887654321**0000**

I have created solution to this issue  by  using " json-bigint" , please let me know if you are ready to accept it after reviewing.

**Comment by aacerox** [comment]
Hi
in current version you can create your own serializer/parser for JSON messages applying your solution without the need to modify client code.

Thanks.
