### ISSUE TITLE
Response delay of 30 seconds ?!

### ISSUE THREAD

**Issue by Apollon77** [aacerox/node-rest-client#153]
Hi,

I have a strange problem with the 3.0.7.
I communicate with a climate control device. When I do the POST call using curl the response will come immediately:

```curl http://192.168.178.26/aircon/set_control_info -v --http1.1 -d 'pow=0&mode=7&stemp=23&shum=0&f_rate=A&f_dir=0'; echo
*   Trying 192.168.178.26...
* TCP_NODELAY set
* Connected to 192.168.178.26 (127.0.0.1) port 80 (#0)
> POST /aircon/set_control_info HTTP/1.1
> Host: 192.168.178.26
> User-Agent: curl/7.51.0
> Accept: */*
> Content-Length: 45
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 45 out of 45 bytes
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Content-Length: 11
< Content-Type: text/plain
< 
* Curl_http_done: called premature == 0
* Closing connection 0
ret=OK,adv=
```

When i do the same POST call using your library the response is received after nearly exactly 30 seconds!
I already set the request/responseTimeOuts and played with noDelay and keepAlive but without any change.

Do you have any idea what could be the reason for this?

All GET requests to that device are also answered immediately ... so only POST requests are problematic.

**Comment by Apollon77** [comment]
I debugged a bit more and it really seems that the on("data" .. is called after 30 seconds ... so there is some kind of tcp timeout somewhere?!

I added debug logging in on("data":

```  
NRC 14:2:5 [NRC CLIENT] ->  +30s GOT DATA <Buffer 72 65 74 3d 4f 4b 2c 61 64 76 3d>
```

Always that way ... independent what I change :-(

**Comment by Apollon77** [comment]
The relevant request looks like:

```
    var data = {
        'data':    {'pow': 0, 'mode': 7, 'stemp': 23, 'shum': 0, 'f_rate': 'A', 'f_dir': 0},
        'headers': {
            'Content-Type': 'application/x-www-form-urlencoded'
        },
        'requestConfig': {
            'timeout':   1000, //request timeout in milliseconds
            'noDelay':   true, //Enable/disable the Nagle algorithm
            'keepAlive': false, //Enable/disable keep-alive functionalityidle socket.
            //keepAliveDelay: 1000 //and optionally set the initial delay before the first keepalive probe is sent
        },
        'responseConfig': {
            'timeout': 1000 //response timeout
        }    };
    this.restClient.post('http://' + this.ip + '/aircon/set_control_info', data , function (data, response) {
        parseResponse(data, 'response', callback);
    });

```

I have rebuild the same request directly with "request" and it returns immediately!

```
var request = require('request');

// Set the headers
var headers = {
//    'User-Agent':       'Super Agent/0.0.1',
    'Content-Type':     'application/x-www-form-urlencoded'
}

// Configure the request
var options = {
    url: 'http://192.168.178.26/aircon/set_control_info',
    method: 'POST',
    headers: headers,
    form: {'pow': 0, 'mode': 7, 'stemp': 23, 'shum': 0, 'f_rate': 'A', 'f_dir': 0}
//pow=0&mode=7&stemp=23&shum=0&f_rate=A&f_dir=0
}

// Start the request
request(options, function (error, response, body) {
    if (!error && response.statusCode == 200) {
        // Print out the response body
        console.log(body)
    }
})
```

Any help would be great ...

**Comment by aacerox** [comment]
I'll try to take a look on your question tonight.

**Comment by aacerox** [comment]
I think I've found it. 

There was a bug on content-length setting after serializer/parsers improvement. This bug is fixed in current version (3.1.0), please try it out and let me know.

Thanks.

**Comment by Apollon77** [comment]
cool ... I'm not at home today but will test tomorrow evening! Thank you, you are great!

**Comment by Apollon77** [comment]
Update: Short test from remote shows that it worked well ... will do depper tests tomorrow and if approved then I close here. Great work!
BTW: Just now saw that you enhanced your first comment ... soory got no notify on tah edit :-( but glad you found it
