### ISSUE TITLE
how to ignore invalid ssl certificate and proceed forward

### ISSUE THREAD

**Issue by rajashekhargundeti** [aacerox/node-rest-client#162]
Hi,
I'm getting the following error while connecting to a site having invalid certicate.
Error: unable to get local issuer certificate.

Please let me know how to ignore this and proceed with this.

-- Raja

**Comment by Senseye** [comment]
Quick fix, add this line before making a request:
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";

**Comment by rajashekhargundeti** [comment]
Thank you, i know this fix. it doesn't solve this problem as the piece of
code is running on a webserver, contacting an outside API to pull and push
the data. I dont wish to change this at nodejs process level.

--Raja

**Comment by rajashekhargundeti** [comment]
Had gone through all the code.

The following statement made this possible:

var c = new Client({connection: {rejectUnauthorized: false}});
