### ISSUE TITLE
JSON type not detected properly

### ISSUE THREAD

**Issue by kdekooter** [aacerox/node-rest-client#34]
On of the services my app relies upon suddenly changed the mime type to `application/json;odata=verbose;charset=utf-8` (probably some redmondish attempt to screw up something not invented by them).

As a result the body of the message is not interpreted as JSON anymore. So we should either match this obscure mimetype, or match on a substring.

**Comment by sherpya** [comment]
what about different charset?
`application/json;charset=ISO-8859-1`,

I think you should parse the header and keep the charset or maybe convert to utf8, like this module https://www.npmjs.com/package/content-type
