### ISSUE TITLE
Accessing data details in data js object

### ISSUE THREAD

**Issue by quiquee** [aacerox/node-rest-client#53]
Hello,

I am trying to show some log message when a post successfully completes and I am using the data 
object passed to the POST callback. If I log the whole of data, then it shows ok, if I log only the data.name property , then it shows undefined. I include the code below.

If this the expected behaviour?

var Client = require('node-rest-client').Client;
var client = new Client();
var args = {
            data: { name:  "Jose",
                    fname: "Perez",
                    email: "Jose.Perez@mail.com" , },
            headers:{"Content-Type": "application/json"} 
        };
        //console.log(i, rows[i].name);

client.post("http://localhost:3000/player", args, function(data,response) {

```
// This shows undefined ????
console.log(data.name);

// This shows OK
// {"id":10,"name":"Jose",....}
console.log(data);
```

});

**Comment by martinib77** [comment]
I'm using node-rest-client@1.5.1 (iis express server) and had the same problem
Tried changing the mimetypes options but was ignored.
Only solution was to edit node-rest-client.js and add the space value to the jsonctype.
