### ISSUE TITLE
delete method is not working well

### ISSUE THREAD

**Issue by rkmax** [aacerox/node-rest-client#64]
I'm building this request

```
DELETE /rest/service/5117 HTTP/1.1
Host: localhost:8080
Authorization: Basic bXl1c2VyOm15cGFzc3dvcmQ==
Cache-Control: no-cache
```

```js
var Client = require('node-rest-client').Client

var defaultOptions = {
    headers: [{"Content-Type": "application/json"}],
    user: 'myuser',
    password: 'mypassword',
    mimetypes: {
        json: ["application/json", "application/json;charset=utf-8"]
    }
};

var client = new Client(defaultOptions);

client.delete('http://localhost:8080/rest/service/5117', function(data, response) { ... }); // always returns 400
```

if i use the module request works fine

```js
var options = {
        method: 'DELETE',
        uri: 'http://localhost:8080/rest/service/5117',
        headers: {"Content-Type": "application/json", "Authorization": "Basic bXl1c2VyOm15cGFzc3dvcmQ=="}
};

    request(options, function(err, response, body) {....}); // works fine!
```

**Comment by aacerox** [comment]
could you please try this?

```javascript

var Client = require('node-rest-client').Client

var defaultOptions = {    
    user: 'myuser',
    password: 'mypassword',
    mimetypes: {
        json: ["application/json", "application/json;charset=utf-8"]
    }
};

var client = new Client(defaultOptions);

var args ={headers:{"Content-Type": "application/json"}};

client.delete('http://localhost:8080/rest/service/5117',args, function(data, response) { ... }); 

```

**Comment by rkmax** [comment]
@aacerox same problem

Here are the requests

## Generated by client.delete
```
DELETE /rest/service/5117 HTTP/1.1
Host: localhost:8080
Authorization: Basic dXNlcjpwYXNzd29yZA==
Connection: keep-alive
Transfer-Encoding: chunked

0
```

## Generated by request (working)

```
DELETE /rest/service/5117 HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Authorization: Basic dXNlcjpwYXNzd29yZA==
content-length: 0
```

**Comment by aacerox** [comment]
hi @rkmax 

I've tried DELETE method several times with different REST sites and works without problems. for example:

```javascript
var Client = require('node-rest-client').Client;
var defaultOptions = {    
    user: 'myuser',
    password: 'mypassword',
    mimetypes: {
        json: ["application/json", "application/json;charset=utf-8"]
    }
};

var client = new Client(defaultOptions);

var args ={headers:{"Content-Type": "application/json"}};

client.delete('http://jsonplaceholder.typicode.com/posts/1',args, function(data, response) { 

	console.log(data);
 }); 
```
I see your testing against a local server. Is it private or are you using any that I can download to try by my self? 

How do you get the requests logs you sent me the last comment?

Thanks.

**Comment by rkmax** [comment]
@aacerox i using for communicate with activiti.org activiti-rest.

I ge the request logs using http://www.charlesproxy.com/

**Comment by aacerox** [comment]
the activity REST API documentation mention this:
```
Due to default security properties on Tomcat, escaped forward slashes (%2F and %5C) are 
not allowed by default (400-result is returned). This may have an impact on the deployment 
resources and their data-URL, as the URL can potentially contain escaped forward slashes.

When issues are experienced with unexpected 400-results, set the following system-property: 
-Dorg.apache.tomcat.util.buf.UDecoder.ALLOW_ENCODED_SLASH=true.
```

could you check to set this property an see if it works? I know you're not using escaped forward slashes in your URL but I need to discard possible causes.

Also you can enable debug on the client by setting the env variable debug and send me the result

````
linux: export DEBUG=true

windows:set DEBUG=true

```

**Comment by rkmax** [comment]
@aacerox i'm using Glassfish

**Comment by ncorison** [comment]
FYI: I am having the same problem. Interestingly, changing the method from DELETE to GET and the call works fine; change it back to DELETE and it fails. Added "content-length: 0" to my header and it worked!

**Comment by ncorison** [comment]
Please note that the latest version of Apache requires "content-length" in the header or Apache will reject the request with a 500 error - your server will never see the request! I have had issues with node-rest-client's POST and DELETE because of this.

**Comment by aacerox** [comment]
Thanks @ncorison 

Time ago I had a similar problem with nginx and solved it adding Content-Length to every POST and PUT method requests, but I forgot DELETE method (my fault ...).

Tonight I'll set Content-Length header to DELETE method too,  and I'll upload a new version with these changes.

**Comment by aacerox** [comment]
Hi @rkmax and @ncorison 

I've created a branch "issue64-delete-method" with the fix I point to @ncorison in the last post (setting always "Content-length" header in every POST/PUT/DELETE/PATCH method request).

Could you please test your code against this branch to see if we have found a solution?

Thanks.

**Comment by rkmax** [comment]
Thanks @aacerox I'll try it this weekend

**Comment by aacerox** [comment]
Hi @rkmax and @ncorison 

have you been able to test your code agains branch "issue64-delete-method" during the weekend?

**Comment by ncorison** [comment]
No, I have not - it will need to wait until tomorrow at the earliest.

Norman



________________________________

**Comment by ncorison** [comment]
Looks like it's working OK for me.

Norman



________________________________

**Comment by aacerox** [comment]
I assume this is fixed, so I close this issue. If not please reopen.
