### ISSUE TITLE
HTTPS request with self signed certificate on the server

### ISSUE THREAD

**Issue by psinghsp** [aacerox/node-rest-client#66]
If I use the HTTPS client built into node library, I can pass "rejectUnauthorized" to false and node will happily make https request to server with self signed certificate. How can I do this with node-rest-client? I could not see this in the source code.

**Comment by aacerox** [comment]
Hi
but rejectUnauthorized isn't a server parameter?

a quote from node docs say:

__*rejectUnauthorized:*__ A boolean indicating whether a __server__ should automatically reject clients with invalid certificates. Only applies to __servers__ with requestCert enabled.

Could you please tell me how do you set that parameter in https node client?

Thanks.

**Comment by psinghsp** [comment]
rejectUnauthorized is one of the HTTPS client options. It allows a client to talk to a server with self-signed certificate.

I did figure this out for node-rest-client library. Here is the example from my code:

   var options = {
        connection: {
            rejectUnauthorized: false,
            headers: {
                "Content-Type": "application/json"
            }
        },
        requestConfig: {
            timeout: 60000,
            noDelay: true,
            keepAlive: true,
            keepAliveDelay: 1000
        },
        responseConfig: {
            timeout: 300000
        }
    };

    var tmpClient = new Client(options);

**Comment by aacerox** [comment]
You're right that's the way to pass the "options" parameter to http.request or https.request methods with node-rest-client. I understand that with the example you post, the issue is solved, right?

thanks.

**Comment by fzimbeck** [comment]
I had same issue and connection options in this example help me to fix it, thanks!
