### ISSUE TITLE
Mocking Client in unit tests

### ISSUE THREAD

**Issue by anton-johansson** [aacerox/node-rest-client#71]
I'm using node-rest-client for my project and I've come to the point where I want to start unit testing my classes that utilize node-rest-client. Is there any examples on how I can mock the Client in my tests? For example, my class might look like this:

```
SomeClass.prototype.execute = function(orderId)
{
	var deferred = q.defer();
	var self = this;

	this.client.get(endpoint + '/orders/' + orderId, args, function(responseData, response)
	{
		if (response.statusCode === 200)
		{
			deferred.resolve(responseData);
		}
		else
		{
			deferred.reject(new Error('Error occurred'));
		}
	})

	.on('error', function(error)
	{
			deferred.reject(new Error('Error occurred'));
	});

	return deferred.promise;
};
```

`this.client` is a Client instance, and I'm using [q](https://github.com/kriskowal/q) for promises.

How can I easily mock the clinet so I reach the three scenarios? The three scenarios are:
* Successful HTTP request with statusCode 200
* Successful HTTP request with statusCode anything else than 200
* Unsuccessful HTTP request (which leads to the .on('error', ...) handler

**Comment by flosky** [comment]
Hi, I'm having trouble unit testin my code with node-rest-client too.

I want to mock a GET rest call, so I try this in my test file using sinon stubs:

    var Client = require('node-rest-client').Client;
    var client = new Client();
    
    sinon.stub(client, 'get');

But when I run the tests the get call is still executed to the real url and the stub is not used. I suppose that is because I create a new client with *new*. So I would have to create the stub on the *Client* Object, but I don't seem to be able to access the method 'get' then.

So what I would like to do is sth like this:

    sinon.stub(Client, 'get');

or

    sinon.stub(Client.prototype, 'get');

Could you please help me with created a stub Object that I can use to run my tests without making any real REST calls?

Thank
Flosky

**Comment by jtiai** [comment]
Only way I got mocking working was to actually mock instantiated class itself.

**Comment by anton-johansson** [comment]
Yes, it's the instansiated class I want to mock. But I'm not sure how to do it best, considering the promises, such as ```.on('error', function(error) { ... });```

**Comment by jtiai** [comment]
Problem is that node rest client uses class method generation in the class constructor - which causes the issue that all methods are always recreated per instance - thus making mocking them impossbile through prototype.

My suggestion would be moving (at least) all methods (get/post/put/patch/delete) as a prototype definition from constructor.

So this is how I did it for time being.

First I created a small stub that mimics object returned from call. Inner on is required for error handler.

```javascript
var restResponseMock = function(data, statusCode) {
    return function(url, opts, cb) {
        cb(data, {statusCode: statusCode || 200});
        return {
           on: function() {
           }
        };
    }
}
```

And then in my test case:

```javascript
    var clientGetMock = sinon.stub(rest_client, 'get', restResponseMock({data: 'FooBar'}, 200));
```

Note that client must be actual instance you use in your code, so either you declare it at module level and export it (which I did):

```javascript
var Client = require('node-rest-client').Client;
var rest_client = new Client();

/* 
 * <some code you want to test here>
*/

module.exports.rest_client = rest_client; // This is needed for tests

```

**Comment by anton-johansson** [comment]
Looks good! And if you would want to mock the on('error') flow, how would you do? I would want it to call my callback for the 'error' event, to simulate this flow.

**Comment by jtiai** [comment]
I used EventEmitter and process.nextTick to emit error event - not sure is that correct way to do it...

```javascript
var restErrorMock = function(data) {
    return function(url, opts, cb) {
        var eventEmitter = new events.EventEmitter();
        process.nextTick(function() {eventEmitter.emit('error', data)});
        return eventEmitter;
    };
}
```

And in a test case:

```javascript
var clientGetMock = sinon.stub(rest_client, 'get', restErrorMock(new Error("DARN!")));
```

**Comment by anton-johansson** [comment]
Thanks for the examples!

**Comment by haribabupuppala** [comment]
Hi Anton Johansson

I am not able to test using the above mentioned approach.

Kindly request you to please share some sample test case that you tested for node-rest-client.

This will really help me to resolve my issues, 

Thanks
Hari.

**Comment by pradeep20mce** [comment]
Thank you jtiai. Your solution worked very well.

**Comment by upreddy** [comment]
Hi,
I am also not able to test using the above approach. Can any one Please help me on how to mock node-rest-client request.
