### ISSUE TITLE
Binary data decoded as UTF-8

### ISSUE THREAD

**Issue by smarx** [aacerox/node-rest-client#72]
https://github.com/aacerox/node-rest-client/blob/master/lib/node-rest-client.js#L396

This line seems to always call `toString()` on the Buffer response from the server. My understanding is that this will interpret the data as UTF-8 and thus corrupt binary data.

I believe gzipped data from the server may avoid this problem. Is there some way to download non-gzipped binary data using node-rest-client?

**Comment by aacerox** [comment]
Hi @smarx 
I've created a branch called "issue64-delete-method" to fix another issue but I've reused it to try to fix yours too. So please could you test your code against this branch to see if you can download binary content without corruption?

Thanks.

**Comment by smarx** [comment]
Thanks for the quick response, @aacerox. I tested the code in the `issue64-delete-method` branch, and everything worked!

**Comment by aacerox** [comment]
Ok, I'll upload a new version tonight with this fix.

Thanks.
