### ISSUE TITLE
Content-Type detection problem

### ISSUE THREAD

**Issue by evangelion1204** [aacerox/node-rest-client#75]
Hi,

creating a simple REST-Service with express and using this lib I encountered the problem, that the result is not parsed as JSON although one is returned and the content type was set.

Currently the code checks for

```javascript
"jsonctype":["application/json","application/json;charset=utf-8"]
```

but express created `application/json; charset=utf-8`, simply adding a third element in the list is helping in that case or changing the detection with a split and comparing each element after having trimmed it.

If you wish I can drop a PR later, depending which solution you prefer or maybe you have another one in mind.

Kind regards,

Michael

**Comment by aacerox** [comment]
Hi @evangelion1204 

You can set a custom content-type for json or xml  using the "mimetypes" initialization parameter. Please refer to documentation (https://github.com/aacerox/node-rest-client#options-parameters) and issues #17 and #12  

Thanks.
