### ISSUE TITLE
Missmatch Header String in 'Content-Type'

### ISSUE THREAD

**Issue by htresch** [aacerox/node-rest-client#84]
# JSON string is delivered as Buffer!
### version = 1.5.1

The problem is mainly the check function "isJSON" for the "content-type" property. The following hard coded search strings are being expected.

Please check the line in "node-rest-client.js"
Line: 339
```javascript
	var ConnectManager = {
		"xmlctype":["application/xml","application/xml;charset=utf-8"],
		"jsonctype":["application/json","application/json;charset=utf-8"],
```
Note that there is no whitespace between "application/json" and "charset=utf-8" in the second item of the array.

But our target express-server delivers the response header as following:
```javascript
"application/json; charset=utf-8"
```
It has a whitespace between two properties, and eventually, there occurs no string matching.

**Comment by aacerox** [comment]
please refer to issue #75 to find a solution to this issue.

Thanks.
