### ISSUE TITLE
followRedirect ignored

### ISSUE THREAD

**Issue by andrewslack** [aacerox/node-rest-client#87]
var args = {
...
                requestConfig:{
                    followRedirect: true
                }
            };

What is the support for followRedirect?  I've set it in the hope that is set like it is with 'http' requests as referenced here: 

var request = require('http');
request({
  followRedirect: true,
  url: url
}, function (error, response, body) {
  if (!error) {
    console.log(response);
  }
})

Thanks.

**Comment by schulzetenberg** [comment]
If this issue is still open, does that mean there is possibility of including it in a future release?

**Comment by aacerox** [comment]
will be included in next release planned before christmas

thnx
