### ISSUE TITLE
unexpected data response

### ISSUE THREAD

**Issue by chisleu** [aacerox/node-rest-client#94]
I'm getting an unexpected data response from a solr query.

The url is ```http://localhost:8983/solr/posts/query?q=*%3A*```

It works as expected when accessed directly, returning a json response.

However that url through client.get is causing data to be set to a Buffer of some sort:

Any help is appreciated. Here is the data object. The response object is too many pages of information.
```
{
  "type": "Buffer",
  "data": [
    123,
    10,
    32,
    32,
    34,
    114,
    101,
    115,
    112,
    111,
    110,
    115,
    101,
    72,
    101,
    97,
    100,
    101,
    114,
    34,
    58,
    123,
    10,
    32,
    32,
    32,
    32,
    34,
    115,
    116,
    97,
    116,
    117,
    115,
    34,
    58,
    48,
    44,
    10,
    32,
    32,
    32,
    32,
    34,
    81,
    84,
    105,
    109,
    101,
    34,
    58,
    52,
    44,
    10,
    32,
    32,
    32,
    32,
    34,
    112,
    97,
    114,
    97,
    109,
    115,
    34,
    58,
    123,
    125,
    125,
    44,
    10,
    32,
    32,
    34,
    114,
    101,
    115,
    112,
    111,
    110,
    115,
    101,
    34,
    58,
    123,
    34,
    110,
    117,
    109,
    70,
    111,
    117,
    110,
    100,
    34,
    58,
    48,
    44,
    34,
    115,
    116,
    97,
    114,
    116,
    34,
    58,
    48,
    44,
    34,
    100,
    111,
    99,
    115,
    34,
    58,
    91,
    93,
    10,
    32,
    32,
    125,
    125,
    10
  ]
}
```

**Comment by rikanulo** [comment]
I've had the same issue. These are weirdly just ASCII decimal codes. Your combination reads:
```
{
"responseHeader":{
"status":0,
"QTime":4,
"params":{}},
"response":{"numFound":0,"start":0,"docs":[]
}}
```
This doesn't seem to be a ```node-rest-client```'s issue, however, since it uses ```http``` and ```https``` packages for all its requests, and making the request directly through them results in the same response. You can do ```response.setEncoding('utf8');``` using ```http``` to see the actual text shown above, which should help your debugging process.

**Comment by chisleu** [comment]
I'm not really debugging anything. That is a valid json response from solr. I was simply following the simple rest client guide in the README.md, but "data" isn't being decoded from json into an object as it says in the README.

I switched to using the requests library to solve my problem.

**Comment by rikanulo** [comment]
So did I :)

**Comment by ernie58** [comment]
This solved my problem:

    client = new Client(
        {
            mimetypes: {
                json: ["application/json", "application/json;charset=utf-8", "application/json; charset=utf-8"]
            }
        }
    );

Express.js uses the third json mime-type, node-rest-client expected the second (without a space), adding that third made node-rest-client parse the buffer into json object
