### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by azcn2503** [aacerox/node-rest-client#97]
Occasionally, when using client.get, an unhandled error will stop my application:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: read ECONNRESET
    at errnoException (net.js:904:11)
    at TCP.onread (net.js:558:19)
```

The code that throws this exception, but only sometimes:

    client.get('http://somewebsite.com', function(data, response) { }

It would be great if the error could be handled so I could see a detailed error message explaining why this is happening.

**Comment by battlecow** [comment]
+1

**Comment by aacerox** [comment]
have you seen request error handler? please refer to  [documentation](https://github.com/aacerox/node-rest-client/blob/master/readme.md#error-handling)
