### ISSUE TITLE
Fuzzy recognition of content type

### ISSUE THREAD

**Issue by marcelboettcher** [aacerox/node-rest-client#98]
Hey. thanks for the awesome project! I like using it!

An external service I call returns `Content-Type: application/json; charset=utf-8` (notice the space before charset) and therefore the binary data is not parsed to JSON. 
I recommend making the comparison more fuzzy and just check if the Content-Type **contains** "application/json" after making it lower case (as you already do).

Do you agree? 

Looking forward to the next release. Thx!
Marcel

**Comment by aacerox** [comment]
fixed with pull request

**Comment by aacerox** [comment]
fixed with pull requests

**Comment by marcelboettcher** [comment]
Thx a lot!
